{
 "title": "College_Reporting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Student", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Student",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "rawSql": "select count(*) from student;" }
   ]
  },
  {
   "title": "Computer Science ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM student\nwhere branch='CS';"
    }
   ]
  },
  {
   "title": "mechinal ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM student\nwhere branch='ME';"
    }
   ]
  },
  {
   "title": "electrical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM student\nwhere branch='EEE';"
    }
   ]
  },
  {
   "title": "Civil",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM student\nwhere branch='Civil';"
    }
   ]
  },
  {
   "title": "Boys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select count(gender) \nfrom student\nwhere gender='Male';\n"
    }
   ]
  },
  {
   "title": "Girls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "select count(gender) \nfrom student\nwhere gender='Female';"
    }
   ]
  },
  { "title": "Faculty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Faculty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "select count(*) from faculty;" }
   ]
  },
  {
   "title": "CS Department",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM faculty\nwhere branch='CS';"
    }
   ]
  },
  {
   "title": "ME Department",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM faculty\nwhere branch='ME';"
    }
   ]
  },
  {
   "title": "EEE Department",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM faculty\nwhere branch='EEE';"
    }
   ]
  },
  {
   "title": "Civil Department",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(branch) AS \"branch\"\nFROM faculty\nwhere branch='Civil';"
    }
   ]
  },
  {
   "title": "Gents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select count(gender) \nfrom faculty\nwhere gender='Male';\n"
    }
   ]
  },
  {
   "title": "Ladies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "rawSql": "select count(gender) \nfrom faculty\nwhere gender='Female';"
    }
   ]
  }
 ]
}